services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=22
    container_name: api
    env_file: [.env.docker]
    ports:
      - "5555:5555"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
